### ISSUE TITLE
Make class extends and implements prettier by fitting to line width

### ISSUE THREAD

**Issue by thorbenvh8** [thorbenvh8/prettier-java#13]
https://github.com/thorbenvh8/prettier-java/blob/master/PREVIEW.md#extends_abstract_class_and_implements_interfaces

`public class ExtendsAbstractClassAndImplementsInterfaces extends AbstractClass implements Interface1, Interface2 {`
It's just a line right now, when doesn't fit line, it should look like this? (open for discussion @azz)

public class ExtendsAbstractClassAndImplementsInterfaces
*indent* extends AbstractClass
*indent* implements Interface1,
*same pos as Inter1* Interface2
{`
(formatting code in an issue is hard?!)

**Comment by j-f1** [comment]
You could check out [how it’s implemented in TypeScript](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgKIAe8UAJpgIIBGmMATumDAMIbbmkCSAtgA6pxcEMTB1hxaAMwZxccIgjI4qNeoxZZcAS179BsXKPiTpARgA0OQ+Klg4AJhzAAOlAC+IMyAg8Ym6JmRQdFpaCAB3AAVghACUdAA3CE0SDxAsGGQpVEw4T0pVAGs4GABlHgZNKABzZDoAV1yQEggwTPRsxsqc2hgI+iqudDaOzwArTAIAIULikvRBABlKuGGczwg6mB5Nu1XG8tpu5BAYAE8eGTBaTR9UnmvYAHVkmAALZAAOAAZPe4gcx70HjHe4ycTxFaeWhwACOdU00L66AGQyQWTWIByXE0tVoDU8mEqVX4AEU6hB4HtPDB0JRniQ3sg7NT6JpUESmBAuINjlBoJCQHUcgAVWmxdFwVyuIA) for inspiration.

**Comment by thorbenvh8** [comment]
its just the same as i have, but is that really cool and readable?

**Comment by j-f1** [comment]
> is that really cool and readable?

It might not be, but since people probably shouldn’t be writing code that’s that long, they should be willing to accept the result.

**Comment by thorbenvh8** [comment]
From my experience its pretty common to have a class that extends and has at least 2 interfaces to implement. Actually that what you should love about java :)
I will work on this one on the next weekend and show you the output. Maybe I can convince you :)
Thanks for your feedback, I really appreciate this fast feedback!

**Comment by j-f1** [comment]
I was just going by my TS knowledge (I don’t know Java, I’m just attempting to help based on what I know of other languages).

**Comment by thorbenvh8** [comment]
I'm very grateful for your feedback, I hope I didn't come off wrong.

**Comment by thorbenvh8** [comment]
@j-f1 Please check this :)
https://github.com/thorbenvh8/prettier-java/blob/master/PREVIEW.md#extends_abstract_class_and_implements_interfaces
I find it really pretty and would really appreciate this in my projects like this :)

**Comment by j-f1** [comment]
That looks really nice! If you have time, would you be willing to contribute that style to the JS printer? [The current style](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgKIAe8UAJpgIIBGmMATumDAMIbbmkCSAtgA6pxcEMTB1hxaAMwZxMAHSg5FOOEQRkcVGvUYsschUoCWvfoNj6llnKPiTpARgA08q0pvipYOACZnB1+52XgDMfq6KgZ5wACw4wAC+II4gEDwwhtCYyKDotLQQAO4ACrkIWSjoAG4QhiRJIFgwyFKomHDJlNoA1nAwAMo8DIZQAObIdACu7SAkEGDN6K3Tw220MEX0I1zoC0vJAFaYBABC3b196IIAMsNwu23JEBMwPM-e99ODtKvIIJTolAAnqhoPUeLRhjAAOq1GAAC2Q3gADMlwRA2lD6DxfuCZOJKndkrQ4ABHCaGYkbdBbHZIFoPEBtLiGca0KbJTDDEb8ACKEwg8A+yRgAJhJHhiOF9EMqC5TAgXG2vyg0EJIAmbQAKgDyvS4PF4kA) is not as nice.

**Comment by thorbenvh8** [comment]
It would be an honor for me :)
you mean prettier/prettier project?

**Comment by j-f1** [comment]
Yes, that’s the one.

**Comment by thorbenvh8** [comment]
@j-f1 I implemented it here in my own fork branch :)
https://github.com/thorbenvh8/prettier/tree/extends_implements
can you please check? I actually changed 148 snapshots...

**Comment by thorbenvh8** [comment]
I made it so it always adds a hardline before extends and implements no matter how long the line

**Comment by j-f1** [comment]
> I made it so it always adds a hardline before extends and implements

That doesn’t look as nice IMO — it should only break if needed, especially since implementing multiple interfaces isn’t as common in JS-land.

**Comment by azz** [comment]
Yeah we definitely want to keep the "if it fits, print it" approach.

**Comment by thorbenvh8** [comment]
Ok fixed it :) sorry for the missunderstanding :) Will do this in java too, youre right it makes sense :)
This is the output now :)
<a href="https://ibb.co/f6FZnR"><img src="https://thumb.ibb.co/f6FZnR/Screen_Shot_2018_01_09_at_8_40_09_AM.png" alt="Screen_Shot_2018_01_09_at_8_40_09_AM" border="0"></a>

@j-f1 @azz Im gonna create a pull request from this?

**Comment by j-f1** [comment]
Looks awesome!

**Comment by azz** [comment]
Great stuff! Absolutely open a PR :)

**Comment by thorbenvh8** [comment]
https://github.com/prettier/prettier/compare/master...thorbenvh8:extends_implements?expand=1
I have to fix some tests that are now not working as they were intended :) then I will create a PR :)

**Comment by thorbenvh8** [comment]
Side question why does the ci pipeline in travis takes 52 mins?
