### ISSUE TITLE
Fix empty method pretty print

### ISSUE THREAD

**Issue by thorbenvh8** [thorbenvh8/prettier-java#14]
https://github.com/thorbenvh8/prettier-java/blob/master/PREVIEW.md#empty_method

**void method() {}**

~~*or*~~

~~void method() {~~
~~}~~

**Comment by j-f1** [comment]
It looks like it’s [collapsed](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgKIC2ADjAJ4CycMAFhACY7AA6ULO7ORArgEaoCWYHJhjoYgnAXT8oACnQAnAOaYkwmAplKA2gF0AlGoBuEfg2ZQOOAL4s2HTFNSpZh9Zqg7dje+1usofxAAGhAIEn5oTGRQRQUIAHcABUUEaJR0EzMQkCwYZAAzdFRMOFCeBXQwAGsqAGUiKq1kDS4ykDoIMELi0tCZUoUYJMqlKR6S9oArTAAPACFKmvr0AjgAGRk4Cb6wrhhuGAAmHfbGhUHkEDIiOEwwTRIcog8YAHUzGmQADgAGUJeEFKb0qRCuLzucAURm2oQUcAAjlx+PCRugxuhTqFSgR+C0FG1sVpUHAAIpcCDwLHXdA8D50L5II6hDTSASeADCEAI4xQUGgsJAXFKABVaekipNrNYgA) in TS.

**Comment by thorbenvh8** [comment]
ok we should do it like that then :)
