### ISSUE TITLE
Bundle the plugin correctly to npm

### ISSUE THREAD

**Issue by thorbenvh8** [thorbenvh8/prettier-java#15]
Publishing the plugin to npm isn't bundling it correctly together? Right now its only the index.js is uploaded?
Never done this before, so have to figure out how to do this

https://github.com/prettier/prettier/issues/3744

**Comment by azz** [comment]
If you run `npm pack ` it will create a tar file which will be the same as what is published, you can inspect the package that way. It shouldn't really be the plugins responsibility to bundle into a single file, we'll find a better way to do that.

**Comment by azz** [comment]
At first glance it looks OK

https://bundle.run/prettier-plugin-java@0.0.1

**Comment by thorbenvh8** [comment]
Ok great :)
