### ISSUE TITLE
Always add block statement after if condition

### ISSUE THREAD

**Issue by thorbenvh8** [thorbenvh8/prettier-java#28]
```java
if (true) 
   doSomething();
```
=>
```java
if (true) {
   doSomething();
}
```

**Comment by j-f1** [comment]
We don’t do this for JS because it alters the AST, and we prefer to defer to a inter for AST-modifying operations. As such, you may not want to do this for Java either.

**Comment by thorbenvh8** [comment]
@j-f1 thanks for the feedback,
but isn't that bad coding style, and easily fixed to make collaboration and maintainability easier?
And there is not linter for java

**Comment by j-f1** [comment]
> but isn't that bad coding style, and easily fixed to make collaboration and maintainability easier?

Some people find it easier to read this:

```js
function foo() {
  if (!bar) return;
  // ...
  if (!baz) return;
  // ...
  if (!quux) return;
}
```

than this:

```js
function foo() {
  if (!bar) {
    return;
  }
  // ...
  if (!baz) {
    return;
  }
  // ...
  if (!quux) {
    return;
  }
}
```

**Comment by bd82** [comment]
Does prettier for JavaScript even have options to choose between those two alternatives?

**Comment by j-f1** [comment]
@bd82 No, but it’ll preserve whichever one you use.

**Comment by bd82** [comment]
Oh I see.

**Comment by thorbenvh8** [comment]
@j-f1 Ok we will keep it the way it is then :)
Maybe later when we have options for plugins, we can make it available :)
