### ISSUE TITLE
Printing should be call path.call or path.map

### ISSUE THREAD

**Issue by azz** [thorbenvh8/prettier-java#3]
👋 @thorbenvh8,

Great work on this so far! I've just raised a couple of minor issues but this is the main one :wink:

I noticed you're not preserving the FastPath data structure. You should preserve this structure as it gives you a lot of stuff for free, like being able to read ancestor nodes, getting comment support, and embedding support.

Here's an example from Prettier HTML:

https://github.com/prettier/prettier/blob/5e2e7a2881d07ff0aa4b4673becc9cb4ce2f6cae/src/language-html/printer-htmlparser2.js#L97-L104

```js
function printAttributes(path, print) {
  const node = path.getValue();

  return concat([
    node.attributes.length ? " " : "",
    indent(join(line, path.map(print, "attributes")))
  ]);
}
```

Note that instead of `node.attributes.map(printAttribute)`, it is `path.map(print, "attributes")`. This way each AST node enters the main `genericPrint` switch block.

There's more info here: https://github.com/prettier/prettier-php/issues/12 and we'll document this better soon.

As a side note, you should also delete `_util-from-prettier.js` and update the heading in the README :)

**Comment by thorbenvh8** [comment]
Thanks for the feedback so fast!
Updated readme and removed _util-from-prettier.js and moved printer/index.js to printer.js

**Comment by thorbenvh8** [comment]
For the other stuff I have to spin my head around it :)
But we will def do that, until then this tickets stays open

**Comment by thorbenvh8** [comment]
@azz I have fixed that printing :)
Could you check if I use it correctly? :)
https://github.com/thorbenvh8/prettier-java/commit/590083f256d71110feef8ec88cfbe5590f4e74bd

**Comment by azz** [comment]
Yep, looks great!

**Comment by j-f1** [comment]
FYI @thorbenvh8 you might want to check the email address you’ve configured with Git (`git config --global user.email`) — it’s currently not associated with your account.

**Comment by azz** [comment]
Since this is in master now I'll close this issue.
