### ISSUE TITLE
Groovy

### ISSUE THREAD

**Issue by Graham42** [thorbenvh8/prettier-java#44]
My understanding is that groovy and java are quite similar, curious if this project could also be used to format groovy?
If not, perhaps you could comment on what work would be needed for a prettier-groovy formatter?

Thanks :slightly_smiling_face:

**Comment by bd82** [comment]
## Overview
I think the main effort would be to build a Groovy Parser In JavaScript.
prettier-java relies on [chevrotain-java](https://github.com/thorbenvh8/chevrotain-java) which is a Java Parser in JavaScript built using the [Chevrotain](https://github.com/SAP/chevrotain) parsing library.

The secondary effort will be to build a "printer" for the Syntax Tree produced by the parser.
That re-prints the text is a **pretty** manner.

@thorbenvh8  please correct me if I am wrong.

## Grammar Reuse

I am no expert on groovy, but I doubt you can re-use the Java Parser to parse groovy.
While chevrotain does support grammar inheritance that is normally useful when you want to make slight changes, for example a Java9 parser extending a Java8 parser.

My guess is that the "reuse" would come in the form of copy/pasting code snippets such as
comments/whitespace(NL) handling and using this project as a base template.

## Alternatives

The problem with creating your own Parser is that there are often many edge cases
and a good amount of repetitive work, Parsing libraries can help with that but it can take a while for a new parser implementation to mature enough to actually match the spec 100%.

Some prettier plugins have taken a different approach which is to find an existing Parser for the plugin's language (often implemented in the plugin's language) and serialize its output be later printed
using JavaScript logic. The advantage is that you get a mature parser, but the disadvantage is the requirement for additional runtimes installed on a user's machine (e.g Python).

**Comment by Graham42** [comment]
Ok thanks for for the explanation :smile:

**Comment by acrewdson** [comment]
@Graham42 @bd82 Thanks for this thread. Is there any interest in jump-starting work on this, possibly taking an approach where we'd use [Parrot](http://groovy-lang.org/releasenotes/groovy-3.0.html#Groovy3.0releasenotes-Parrot) for the parser? I'd be interested in helping.

**Comment by bd82** [comment]
@acrewdson I only have a little time to advise on this project currently so I am not looking to start a new large project... :(

**Comment by acrewdson** [comment]
@bd82 no problem, I understand 👍 I'm going to keep it on my radar since a groovy autoformatter has been on my wish-list for some time now, and it seems like using `prettier` would be the way to go at this point, given the momentum it has

(and if others come across this issue and are interested, please speak up)

**Comment by rubixibuc** [comment]
Checking if this effort is still alive. Was searching for this today

**Comment by boris-petrov** [comment]
For anyone following this thread there seem to be a couple of formatters for Groovy:
https://github.com/nice-move/prettier-plugin-groovy
https://github.com/nvuillam/npm-groovy-lint
