### ISSUE TITLE
After formatting comments disappear

### ISSUE THREAD

**Issue by thorbenvh8** [thorbenvh8/prettier-java#6]
The parser currenlty only acknowledges comments ( //, /* ... */ ) but doesn't add them to the AST.
Fixing this problem probably by moving the jsjavaparser java language definition into this project and updating it.

**Comment by azz** [comment]
Would be nice to keep the parser and the printer separate so others can consume it, Maybe open a PR to the parser and see how it goes?

**Comment by j-f1** [comment]
Alternatively, you could fork it and `require` it from your fork.

**Comment by thorbenvh8** [comment]
I have not the most experience with npm packages, how do i do that? How do i get a fork into npm?

**Comment by azz** [comment]
Either you can install directly from github (like this repo does with `prettier/prettier`), or you can publish under a scope, e.g. `@thorbenvh8/java-parser`

**Comment by thorbenvh8** [comment]
ok thanks :)

**Comment by thorbenvh8** [comment]
http://debuggable.com/posts/how-to-fork-patch-npm-modules:4e2eb9f3-e584-44be-b1a9-3db7cbdd56cb
leaving this here for further reading when I do it on the weekend

**Comment by vjeux** [comment]
Prettier has already pretty good handling for comments out of the box. What you need to do is to add all the comments with their raw position in `ast.comments` and prettier will attach them to the right nodes using a good heuristic. Then you need to add special cases for when the heuristic breaks down.

You don't want the comments in the ast.

See https://github.com/prettier/prettier-python/pull/9 for an example of how to wire it up. Note that you'll need to use the fastpath infrastructure in order to benefit from it.

**Comment by thorbenvh8** [comment]
Thanks, I will check it out :)

**Comment by thorbenvh8** [comment]
@vjeux I looked into it, and I think I can't do it the way you suggested.
My parser is based on pegjs, and I can add comments to the ast, but I dont have the raw input.
How does the comments structure need to look like?
`ast.comments = ["Abc", "Def"]`
Something like this?

**Comment by vjeux** [comment]
It's an array of what looks like normal nodes with a type and location.

**Comment by vjeux** [comment]
I need to look at how your parser is setup but usually comments are extracted during the tokenization phase, before turning the tokens into an ast. So you should be able to get the list of tokens and separate the comments from non comments

**Comment by thorbenvh8** [comment]
Yes I have to add that to my parser, I don't have a start and end position though

**Comment by vjeux** [comment]
How do you report syntax errors if you don't have token positions?

**Comment by thorbenvh8** [comment]
The parser gives you feedback by itself.
Pegjs you write a defintion and than it generates a parser for you but without the actual positions of where what was found. You just get the ast. If it couldn't parse it gives you an exception of what it expected and what line.

**Comment by thorbenvh8** [comment]
It seems to work though without start end :)
THanks for this awesome help! I understand it better now and can implement it correctly and with using the prettier functionality already!

**Comment by thorbenvh8** [comment]
finally solved!!! :)

**Comment by vjeux** [comment]
Yay!
